import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReport = (analysis, fileName = "Resume") => {
  const doc = new jsPDF();

  // ===============================
  // HEADER
  // ===============================

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Campus Buddy", 20, 18);

  doc.setFontSize(11);
  doc.text("AI Resume Analysis Report", 20, 24);

  doc.setTextColor(0, 0, 0);

  // ===============================
  // DETAILS
  // ===============================

  doc.setFontSize(12);

  doc.text(`Resume : ${fileName}`, 20, 40);
  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    20,
    48
  );

  // ===============================
  // SCORES
  // ===============================

  doc.setFontSize(18);
  doc.setTextColor(37, 99, 235);
  doc.text("Overall Analysis", 20, 65);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(13);

  doc.text(
    `Overall Score : ${analysis.overallScore}/100`,
    20,
    78
  );

  doc.text(
    `ATS Score : ${analysis.atsScore}%`,
    20,
    88
  );

  // ===============================
  // SECTION TABLE
  // ===============================

  autoTable(doc, {
    startY: 100,
    head: [["Section", "Score", "Status"]],
    body: Object.entries(analysis.sections).map(
      ([section, value]) => [
        section.toUpperCase(),
        `${value.score}%`,
        value.status,
      ]
    ),
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  let y = doc.lastAutoTable.finalY + 15;

  // ===============================
  // STRENGTHS
  // ===============================

  doc.setFontSize(16);
  doc.setTextColor(34, 197, 94);
  doc.text("Strengths", 20, y);

  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  analysis.strengths.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  // ===============================
  // IMPROVEMENTS
  // ===============================

  y += 8;

  doc.setFontSize(16);
  doc.setTextColor(245, 158, 11);
  doc.text("Areas for Improvement", 20, y);

  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  analysis.improvements.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  // ===============================
  // KEYWORDS
  // ===============================

  y += 8;

  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text("Found Keywords", 20, y);

  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  doc.text(
    analysis.keywords.join(", "),
    25,
    y
  );

  y += 15;

  doc.setFontSize(16);
  doc.setTextColor(220, 38, 38);
  doc.text("Missing Keywords", 20, y);

  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  doc.text(
    analysis.missingKeywords.join(", "),
    25,
    y
  );

  // ===============================
  // NEW PAGE
  // ===============================

  doc.addPage();

  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235);
  doc.text("AI Recommendations", 20, 20);

  let yy = 40;

  analysis.recommendations.forEach((rec, index) => {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);

    doc.text(`${index + 1}. ${rec.title}`, 20, yy);

    yy += 8;

    doc.setFontSize(11);

    const lines = doc.splitTextToSize(rec.description, 170);

    doc.text(lines, 25, yy);

    yy += lines.length * 7 + 10;
  });

  // ===============================
  // FOOTER
  // ===============================

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by Campus Buddy AI",
    20,
    285
  );

  doc.text(
    "Version 1.0",
    170,
    285
  );

  doc.save("CampusBuddy_Resume_Report.pdf");
};
